version: 2
project_name: logos

builds:
  - id: lgs
    main: .
    binary: lgs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: logos
    format: tar.gz
    files:
      - lgs
    name_template: logos-{{ .Os }}-{{ .Arch }}

release:
  github:
    owner: codetesla51
    name: logos
  name_template: "v{{ .Version }}"
  extra_files:
    - glob: install.sh

changelog:
  use: git
